version: '3'

services:
  client:
    container_name: projektarbeit_client
    image: ghcr.io/neklas2000/projektarbeit/client:latest
    ports:
      - '127.0.0.1:${APP_PORT}:${NGINX_PORT}'
    expose:
      - '${NGINX_PORT}'
    environment:
      NGINX_PORT: '${NGINX_PORT}'
      API_HOST: '${API_HOST}'
      API_PORT: '${API_PORT}'
    depends_on:
      - api

  api:
    container_name: projektarbeit_api
    image: ghcr.io/neklas2000/projektarbeit/api:latest
    ports:
      - '127.0.0.1:${API_PORT}:${API_PORT}'
    expose:
      - '${API_PORT}'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
    depends_on:
      - database

  database:
    container_name: projektarbeit_database
    image: ghcr.io/neklas2000/projektarbeit/database:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
