version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  frontend_unit_tests:
    working_directory: ~/project/frontend
    docker:
      - image: cimg/node:21.7.3-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome Installation
          command: |
            google-chrome --version
            chromedriver --version
      - checkout
      - restore_cache:
          key: frontend-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: frontend-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run Unit Tests
          command: npm run test:ci

  frontend_build:
    working_directory: ~/project/frontend
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - restore_cache:
          key: frontend-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: frontend-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Building Client
          command: npm run build

  api_unit_tests:
    working_directory: ~/project/api
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - restore_cache:
          key: api-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: api-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run Unit Tests
          command: npx jest --silent

  api_e2e_tests:
    working_directory: ~/project/api
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - restore_cache:
          key: api-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: api-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run e2e Tests
          command: npm run test:e2e

  api_build:
    working_directory: ~/project/api
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - restore_cache:
          key: api-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: api-cache-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Building API
          command: npm run build


workflows:
  frontend_test_and_build:
    jobs:
      - frontend_unit_tests
      - frontend_build:
          requires:
            - frontend_unit_tests

  api_test_and_build:
    jobs:
      - api_unit_tests
      - api_e2e_tests:
          requires:
            - api_unit_tests
      - api_build:
          requires:
            - api_e2e_tests
